name: hello
env: 
  APPLICATION_NAME   : "MyFlask"
  DELPOY_PACKAGE_NAME: "flask-deploy-ver-${{github.sha}}"
  

on:
  push:
    branches:
      - master

jobs:
  my-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print hello in Testing
        run:  echo "Hello, my-testing"
        
      - name: Execure few commands
        run: |
          echo "Hello Message1"
          echo "Hello Message2"
          echo "Application name: ${{env.APPLICATION_NAME}}"

  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]
    
    steps:
      - name: Print hello in Deloy
        run:  echo "Hello, my-deploy"
        
      - name: Printing Deployment package
        run:  echo "Deploy package name is {{env.DEPLOY_PACKAGE_NAME}}"
